services:
  web:
    build:
      context: web_app
    ports:
      - "8000:8000"
    command: node --watch index.js
    volumes:
      - ./web_app:/app
    develop:
      watch: 
        - action: rebuild
          path: web_app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      # bind mount for init.sql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

      # named volume for persistent data
      - db_data:/var/lib/postgresql/data
    
    develop:
      watch:
        - action: rebuild
          path: db/init.sql

volumes:
  db_data:
